<?php

namespace App\Support\Installer;

/**
 * Step 1 of the installer (Module 24): everything checkable before a
 * database connection exists — PHP version/extensions, filesystem
 * writability, and the handful of .env values the rest of the wizard
 * can't safely work around (APP_KEY in particular — see the note below).
 * Nothing here touches the database.
 */
class RequirementsChecker
{
    public const PASS = 'pass';

    public const WARN = 'warn';

    public const FAIL = 'fail';

    /**
     * Matches composer.json's "php": "^8.2".
     */
    private const MIN_PHP_VERSION = '8.2.0';

    /**
     * Every extension an installed Daftri instance actually exercises:
     * pdo/pdo_mysql (the database itself), openssl (ZATCA XAdES signing +
     * encrypted Settings values), mbstring/dom/xml (UBL XML generation,
     * Blade/PDF rendering), gd (QR code generation via endroid/qr-code),
     * curl (ZATCA API + payment gateway HTTP calls), fileinfo (upload
     * validation), bcmath (money-safe arithmetic), ctype/json/tokenizer
     * (Laravel framework itself).
     */
    private const REQUIRED_EXTENSIONS = [
        'pdo', 'pdo_mysql', 'openssl', 'mbstring', 'dom', 'xml',
        'gd', 'curl', 'fileinfo', 'bcmath', 'ctype', 'json', 'tokenizer',
    ];

    /**
     * Directories the app writes to at runtime — every one must be
     * writable by the web server user or the app can't boot at all
     * (bootstrap/cache) or will fail in ways that only surface later
     * (a broken upload, a silently-uncached view).
     */
    private const WRITABLE_PATHS = [
        'storage/app',
        'storage/app/public',
        'storage/framework/cache',
        'storage/framework/sessions',
        'storage/framework/views',
        'storage/logs',
        'bootstrap/cache',
    ];

    /**
     * @return array<int, array{group: string, label: string, status: string, detail: string}>
     */
    public function run(): array
    {
        return array_merge(
            $this->phpVersionCheck(),
            $this->extensionChecks(),
            $this->databaseDriverCheck(),
            $this->writablePathChecks(),
            $this->configurationChecks(),
        );
    }

    public function allPassed(array $results): bool
    {
        return collect($results)->doesntContain(fn ($r) => $r['status'] === self::FAIL);
    }

    private function phpVersionCheck(): array
    {
        $ok = version_compare(PHP_VERSION, self::MIN_PHP_VERSION, '>=');

        return [[
            'group' => __('PHP'),
            'label' => __('PHP version'),
            'status' => $ok ? self::PASS : self::FAIL,
            'detail' => __('Running :version (:min or newer required).', ['version' => PHP_VERSION, 'min' => self::MIN_PHP_VERSION]),
        ]];
    }

    private function extensionChecks(): array
    {
        return array_map(function (string $extension) {
            $loaded = extension_loaded($extension);

            return [
                'group' => __('PHP extensions'),
                'label' => $extension,
                'status' => $loaded ? self::PASS : self::FAIL,
                'detail' => $loaded ? __('Loaded') : __('Not loaded — required.'),
            ];
        }, self::REQUIRED_EXTENSIONS);
    }

    /**
     * pdo_mysql already appears in the hard-required list above; this is a
     * separate, softer check specifically about MySQL/MariaDB reachability
     * being possible at all, surfaced under its own group so Step 1 reads
     * as "Database" the way the spec lists it, not buried under PHP.
     */
    private function databaseDriverCheck(): array
    {
        $ok = extension_loaded('pdo_mysql');

        return [[
            'group' => __('Database'),
            'label' => __('MySQL / MariaDB driver'),
            'status' => $ok ? self::PASS : self::FAIL,
            'detail' => $ok ? __('pdo_mysql is available.') : __('pdo_mysql is not installed — cannot connect to MySQL.'),
        ]];
    }

    private function writablePathChecks(): array
    {
        return array_map(function (string $relative) {
            $path = base_path($relative);
            $exists = is_dir($path);
            $writable = $exists && is_writable($path);

            return [
                'group' => __('Writable directories'),
                'label' => $relative,
                'status' => $writable ? self::PASS : self::FAIL,
                'detail' => ! $exists
                    ? __('Directory does not exist.')
                    : ($writable ? __('Writable') : __('Not writable by the web server user.')),
            ];
        }, self::WRITABLE_PATHS);
    }

    /**
     * APP_KEY deliberately isn't auto-generated by the wizard itself: the
     * session cookie the wizard's own multi-step state rides on is
     * encrypted using it (see EncryptCookies), so a request-time fix would
     * need to take effect before the session middleware already in the
     * pipeline runs. Simplest and safest is to ask for one `php artisan
     * key:generate` up front, same as any other fresh Laravel install.
     */
    private function configurationChecks(): array
    {
        $hasKey = filled(config('app.key'));
        $envWritable = is_writable(base_path('.env')) || (! file_exists(base_path('.env')) && is_writable(base_path()));
        $envExampleExists = file_exists(base_path('.env.example'));

        return [
            [
                'group' => __('Configuration'),
                'label' => __('Application key (APP_KEY)'),
                'status' => $hasKey ? self::PASS : self::FAIL,
                'detail' => $hasKey
                    ? __('Set.')
                    : __('Missing — run "php artisan key:generate" once before installing.'),
            ],
            [
                'group' => __('Configuration'),
                'label' => __('.env file'),
                'status' => $envWritable ? self::PASS : self::FAIL,
                'detail' => $envWritable
                    ? __('Writable — the wizard can save your settings.')
                    : __('Not writable — the wizard cannot save your database and application settings.'),
            ],
            [
                'group' => __('Configuration'),
                'label' => __('.env.example'),
                'status' => $envExampleExists ? self::PASS : self::WARN,
                'detail' => $envExampleExists
                    ? __('Found — used as a template for any keys not yet set.')
                    : __('Not found — the wizard will still work from the current .env.'),
            ],
        ];
    }
}
